// DBDeployer - The MySQL Sandbox
// Copyright © 2006-2018 Giuseppe Maxia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sandbox

// Templates for multiple sandboxes

var (
	start_multi_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
echo '# executing "start"' on {{.SandboxDir}}
{{ range .Nodes }}
echo 'executing "start" on {{.NodeLabel}} {{.Node}}'
{{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/start "$@"
{{end}}
`
	restart_multi_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
{{.SandboxDir}}/stop_all
{{.SandboxDir}}/start_all "$@"
`
	use_multi_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
if [ "$1" = "" ]
then
  echo "syntax: $0 command"
  exit 1
fi

{{range .Nodes}}
echo "# server: {{.Node}} " 
echo "$@" | {{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/use $MYCLIENT_OPTIONS 
{{end}} 
`
	stop_multi_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
echo '# executing "stop"' on {{.SandboxDir}}
{{ range .Nodes }}
echo 'executing "stop" on {{.NodeLabel}} {{.Node}}'
{{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/stop "$@"
{{end}}
`
	send_kill_multi_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
echo '# executing "send_kill"' on {{.SandboxDir}}
{{ range .Nodes }}
echo 'executing "send_kill" on {{.NodeLabel}} {{.Node}}'
{{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/send_kill "$@"
{{end}}
`
	clear_multi_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
echo '# executing "clear"' on {{.SandboxDir}}
{{range .Nodes}}
echo 'executing "clear" on {{.NodeLabel}} {{.Node}}'
{{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/clear "$@"
{{end}}
`
	status_multi_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
echo "MULTIPLE  {{.SandboxDir}}"
{{ range .Nodes }}
nstatus=$({{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/status )
if [ -f {{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/data/mysql_sandbox{{.NodePort}}.pid ]
then
	nport=$({{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/use -BN -e "show variables like 'port'")
fi
echo "{{.NodeLabel}}{{.Node}} : $nstatus  -  $nport ({{.NodePort}})"
{{end}}
`
	test_sb_multi_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
echo '# executing "test_sb"' on {{.SandboxDir}}
{{ range .Nodes }}
echo 'executing "test_sb" on {{.NodeLabel}} {{.Node}}'
{{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/test_sb "$@"
exit_code=$?
if [ "$exit_code" != "0" ] ; then exit $exit_code ; fi
{{end}}
`

	node_template string = `#!/bin/sh
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}

{{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/use "$@"
`

	MultipleTemplates = TemplateCollection{
		"start_multi_template": TemplateDesc{
			Description: "Starts all nodes (with optional mysqld arguments)",
			Notes:       "",
			Contents:    start_multi_template,
		},
		"restart_multi_template": TemplateDesc{
			Description: "Restarts all nodes (with optional mysqld arguments)",
			Notes:       "",
			Contents:    restart_multi_template,
		},
		"use_multi_template": TemplateDesc{
			Description: "Runs the same SQL query in all nodes",
			Notes:       "",
			Contents:    use_multi_template,
		},
		"stop_multi_template": TemplateDesc{
			Description: "Stops all nodes",
			Notes:       "",
			Contents:    stop_multi_template,
		},
		"send_kill_multi_template": TemplateDesc{
			Description: "Sends kill signal to all nodes",
			Notes:       "",
			Contents:    send_kill_multi_template,
		},
		"clear_multi_template": TemplateDesc{
			Description: "Removes data from all nodes",
			Notes:       "",
			Contents:    clear_multi_template,
		},
		"status_multi_template": TemplateDesc{
			Description: "Shows status for all nodes",
			Notes:       "",
			Contents:    status_multi_template,
		},
		"test_sb_multi_template": TemplateDesc{
			Description: "Run sb test on all nodes",
			Notes:       "",
			Contents:    test_sb_multi_template,
		},
		"node_template": TemplateDesc{
			Description: "Runs the MySQL client for a given node",
			Notes:       "",
			Contents:    node_template,
		},
	}
)
