// DBDeployer - The MySQL Sandbox
// Copyright © 2006-2019 Giuseppe Maxia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sandbox

var ndbStartTemplate string = `#!/bin/bash
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
SBDIR={{.SandboxDir}}
BASEDIR={{.Basedir}}
cd $SBDIR

if [ -f cluster_initialized ]
then
    echo "cluster already initialized on $(cat cluster_initialized)"
    exit 0
fi


NUM_NODES={{.NumNodes}}
cluster_port={{.ClusterPort}}

binary_config=ndb_1_config.bin
count=1

while [ -f ${binary_config}.$count ]
do
    rm -f ${binary_config}.$count
    count=$((count+1))
done

$BASEDIR/bin/ndb_mgmd -f config.ini --configdir=$PWD --ndb-connectstring="host=localhost:$cluster_port"
exit_code=$?
if [ "$exit_code" != "0" ] ; then echo "ERROR during initialization" ; exit $exit_code ; fi

if [ -f stopped_cluster ]
then
    rm -f stopped_cluster
fi

for i in $(seq 2 $NUM_NODES)
do
    $BASEDIR/bin/ndbmtd --ndb-nodeid=$i --ndb-connectstring="host=localhost:$cluster_port"
    exit_code=$?
    if [ "$exit_code" != "0" ] ; then echo "ERROR during initialization" ; exit $exit_code ; fi
done

for i in $(seq 1 $NUM_NODES)
do
	echo "executing 'start' on {{.NodeLabel}} $i"
	$SBDIR/{{.NodeLabel}}$i/start 
	$SBDIR/{{.NodeLabel}}$i/load_grants
done
date > cluster_initialized
`

var ndbConfigTemplate string = `
[system]
Name={{.ClusterName}}

{{range .SQLNodes}}
[ndbd]
DataDir={{.SandboxDir}}/{{.NodeLabel}}{{.Node}}/data
HostName=localhost
NodeId={{.Node}}
{{end}}

[ndb_mgmd]
DataDir={{.SandboxDir}}/{{.NodeLabel}}1/data
NodeId=1
HostName=localhost
PortNumber={{.ClusterPort}}

[api]
NodeId=4
HostName=localhost

[api]
NodeId=5
HostName=localhost

[api]
NodeId=6
HostName=localhost
`

var ndbStopTemplate string = `#!/bin/bash
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}

SBDIR={{.SandboxDir}}
BASEDIR={{.Basedir}}
CLIENT_BASEDIR={{.ClientBasedir}}

cd $SBDIR

if [ -f cluster_initialized ]
then
    if [ ! -f stopped_cluster ]
    then
        $CLIENT_BASEDIR/bin/ndb_mgm \
            --ndb-connectstring="host=localhost:{{.ClusterPort}}" -e shutdown
    fi
    touch stopped_cluster
    rm -f cluster_initialized
fi

for i in {{.StopNodeList}}
do
	echo "executing 'stop' on {{.NodeLabel}} $i"
	$SBDIR/{{.NodeLabel}}$i/stop 
done
`

var ndbMgmTemplate string = `#!/bin/bash
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
SBDIR={{.SandboxDir}}
BASEDIR={{.Basedir}}
CLIENT_BASEDIR={{.ClientBasedir}}

$CLIENT_BASEDIR/bin/ndb_mgm \
    --ndb-connectstring="host=localhost:{{.ClusterPort}}" $@
`

var ndbCheckStatusTemplate string = `#!/bin/bash
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
SBDIR={{.SandboxDir}}

$SBDIR/n1 -e 'select * from ndbinfo.nodes'
`

var NdbTemplates = TemplateCollection{
	"ndb_start_cluster": TemplateDesc{
		Description: "NDB start cluster",
		Notes:       "",
		Contents:    ndbStartTemplate,
	},
	"ndb_stop_cluster": TemplateDesc{
		Description: "NDB stop cluster",
		Notes:       "",
		Contents:    ndbStopTemplate,
	},
	"ndb_config_template": TemplateDesc{
		Description: "NDB cluster configuration",
		Notes:       "",
		Contents:    ndbConfigTemplate,
	},
	"ndb_mgm_template": TemplateDesc{
		Description: "NDB cluster manager",
		Notes:       "",
		Contents:    ndbMgmTemplate,
	},
	"ndb_check_status": TemplateDesc{
		Description: "NDB check cluster status",
		Notes:       "",
		Contents:    ndbCheckStatusTemplate,
	},
}
